#include "warnings_push.h"

// std
#include <algorithm>
#include <cstdint>
#include <filesystem>
#include <functional>
#include <iostream>
#include <list>
#include <map>
#include <memory>
#include <set>
#include <sstream>
#include <stdlib.h>
#include <string>
#include <typeindex>
#include <unordered_map>
#include <utility>
#include <vector>
#include <wchar.h>

// fmt
#include <fmt/format.h>

// windows
#ifndef NOMINMAX
#define NOMINMAX
#endif
#ifndef WIN32_MEAN_AND_LEAN
#define WIN32_MEAN_AND_LEAN
#endif
#include <ShlObj.h>
#include <shobjidl.h>
#include <Windows.h>

// boost
#include <boost/algorithm/string/trim.hpp>
#include <boost/any.hpp>
#include <boost/assign.hpp>
#include <boost/scoped_array.hpp>
#include <boost/signals2.hpp>

// Qt
#include <QAbstractButton>
#include <QAction>
#include <QApplication>
#include <QBitmap>
#include <QBuffer>
#include <QCommandLinkButton>
#include <QCoreApplication>
#include <QCryptographicHash>
#include <QDateTime>
#include <QDesktopWidget>
#include <QDialog>
#include <QDialogButtonBox>
#include <QDir>
#include <QDropEvent>
#include <QFile>
#include <QFileInfo>
#include <QFlags>
#include <QGraphicsObject>
#include <QIcon>
#include <QImage>
#include <QLabel>
#include <QLineEdit>
#include <QMainWindow>
#include <QMenuBar>
#include <QMessageBox>
#include <QMetaEnum>
#include <QMetaMethod>
#include <qmetaobject.h>
#include <QMetaObject>
#include <QMetaType>
#include <QMouseEvent>
#include <QMutex>
#include <QMutexLocker>
#include <QNetworkReply>
#include <QObject>
#include <QPlainTextEdit>
#include <QPushButton>
#include <QQmlContext>
#include <QQmlEngine>
#include <QQuickItem>
#include <QQuickWidget>
#include <QRect>
#include <QRegExp>
#include <QRegularExpression>
#include <QResizeEvent>
#include <QSettings>
#include <QShortcutEvent>
#include <QShowEvent>
#include <QString>
#include <QStringList>
#include <QStyle>
#include <QTableWidget>
#include <QTabWidget>
#include <QtDebug>
#include <QTemporaryFile>
#include <QTextCodec>
#include <QTextEdit>
#include <QTextStream>
#include <QTime>
#include <QTimer>
#include <QToolBar>
#include <QToolButton>
#include <QTreeWidget>
#include <QtWinExtras/QtWin>
#include <QUrl>
#include <QUrlQuery>
#include <QVariant>
#include <QVariantMap>
#include <QVersionNumber>
#include <QVBoxLayout>
#include <QWidget>

#include "warnings_pop.h"
